# GitHub Actions workflow to set up Docker and run LinkPanel using Docker Compose

name: LinkPanel Docker Deployment

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Create docker-compose.yml file
      - name: Set up Docker Compose file
        run: |
          echo "services:
            app:
              image: nickslp/linkpanel:latest
              ports:
                - '8080:8080'
              environment:
                - PORT=8080
                - DEBUG_MODE=true
                - PLAIN_PASSWORD=changeme
              volumes:
                - linkpanel:/home/node/app/data

          volumes:
            linkpanel:
              driver: local" > docker-compose.yml

      # Start services using Docker Compose
      - name: Start LinkPanel with Docker Compose
        run: docker-compose up -d

      # Verify the container is running
      - name: Verify container is running
        run: docker-compose ps
